  version: '3.9'  
  services: 
    backend:
      container_name: app_backend
      build: ./server
      ports:
        - 3001:3001
      working_dir: /app-backend
      command: dev 
      volumes: 
        - ./server/src:/app-backend/src
      depends_on:
        db:
          condition: service_healthy
      environment:
        - APP_PORT=3001
        - JWT_SECRET=jwt_secret
        - DB_USER=root
        - DB_PASS=123456
        - DB_HOST=db
        - DB_PORT=3306
      healthcheck:
        test: ["CMD", "lsof", "-t", "-i:3001"]
        timeout: 10s
        retries: 5
    db:
      image: postgres:13
      container_name: db
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=my_password
        - POSTGRES_DB=LinkedIt
      restart: 'always'
      healthcheck:
        test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
        timeout: 10s
        retries: 5